// ─── Country data for community features ─────────────────────────────────────

export interface Country {
  flag: string;
  name: string;
}

/** Full country list — used for community creation */
export const PAISES: Country[] = [
  { flag: "🌍", name: "Internacional" },
  { flag: "🇦🇫", name: "Afeganistão" },
  { flag: "🇦🇱", name: "Albânia" },
  { flag: "🇩🇿", name: "Argélia" },
  { flag: "🇦🇩", name: "Andorra" },
  { flag: "🇦🇴", name: "Angola" },
  { flag: "🇦🇷", name: "Argentina" },
  { flag: "🇦🇲", name: "Arménia" },
  { flag: "🇦🇺", name: "Austrália" },
  { flag: "🇦🇹", name: "Áustria" },
  { flag: "🇦🇿", name: "Azerbaijão" },
  { flag: "🇧🇸", name: "Bahamas" },
  { flag: "🇧🇭", name: "Barém" },
  { flag: "🇧🇩", name: "Bangladesh" },
  { flag: "🇧🇧", name: "Barbados" },
  { flag: "🇧🇾", name: "Bielorrússia" },
  { flag: "🇧🇪", name: "Bélgica" },
  { flag: "🇧🇿", name: "Belize" },
  { flag: "🇧🇯", name: "Benim" },
  { flag: "🇧🇹", name: "Butão" },
  { flag: "🇧🇴", name: "Bolívia" },
  { flag: "🇧🇦", name: "Bósnia e Herzegovina" },
  { flag: "🇧🇼", name: "Botsuana" },
  { flag: "🇧🇷", name: "Brasil" },
  { flag: "🇧🇳", name: "Brunei" },
  { flag: "🇧🇬", name: "Bulgária" },
  { flag: "🇧🇫", name: "Burquina Faso" },
  { flag: "🇧🇮", name: "Burúndi" },
  { flag: "🇨🇻", name: "Cabo Verde" },
  { flag: "🇰🇭", name: "Camboja" },
  { flag: "🇨🇲", name: "Camarões" },
  { flag: "🇨🇦", name: "Canadá" },
  { flag: "🇶🇦", name: "Catar" },
  { flag: "🇰🇿", name: "Cazaquistão" },
  { flag: "🇹🇩", name: "Chade" },
  { flag: "🇨🇱", name: "Chile" },
  { flag: "🇨🇳", name: "China" },
  { flag: "🇨🇾", name: "Chipre" },
  { flag: "🇨🇴", name: "Colômbia" },
  { flag: "🇰🇲", name: "Comores" },
  { flag: "🇨🇬", name: "Congo" },
  { flag: "🇨🇩", name: "Congo (RDC)" },
  { flag: "🇰🇵", name: "Coreia do Norte" },
  { flag: "🇰🇷", name: "Coreia do Sul" },
  { flag: "🇨🇷", name: "Costa Rica" },
  { flag: "🇨🇮", name: "Costa do Marfim" },
  { flag: "🇭🇷", name: "Croácia" },
  { flag: "🇨🇺", name: "Cuba" },
  { flag: "🇩🇰", name: "Dinamarca" },
  { flag: "🇩🇯", name: "Djibouti" },
  { flag: "🇩🇴", name: "República Dominicana" },
  { flag: "🇪🇨", name: "Equador" },
  { flag: "🇪🇬", name: "Egito" },
  { flag: "🇸🇻", name: "El Salvador" },
  { flag: "🇦🇪", name: "Emirados Árabes" },
  { flag: "🇪🇷", name: "Eritreia" },
  { flag: "🇸🇰", name: "Eslováquia" },
  { flag: "🇸🇮", name: "Eslovénia" },
  { flag: "🇪🇸", name: "Espanha" },
  { flag: "🇪🇹", name: "Etiópia" },
  { flag: "🇫🇯", name: "Fiji" },
  { flag: "🇵🇭", name: "Filipinas" },
  { flag: "🇫🇮", name: "Finlândia" },
  { flag: "🇫🇷", name: "França" },
  { flag: "🇬🇦", name: "Gabão" },
  { flag: "🇬🇲", name: "Gâmbia" },
  { flag: "🇬🇭", name: "Gana" },
  { flag: "🇬🇪", name: "Geórgia" },
  { flag: "🇬🇷", name: "Grécia" },
  { flag: "🇬🇹", name: "Guatemala" },
  { flag: "🇬🇳", name: "Guiné" },
  { flag: "🇬🇼", name: "Guiné-Bissau" },
  { flag: "🇬🇾", name: "Guiana" },
  { flag: "🇭🇹", name: "Haiti" },
  { flag: "🇭🇳", name: "Honduras" },
  { flag: "🇭🇺", name: "Hungria" },
  { flag: "🇾🇪", name: "Iémen" },
  { flag: "🇮🇳", name: "Índia" },
  { flag: "🇮🇩", name: "Indonésia" },
  { flag: "🇮🇷", name: "Irão" },
  { flag: "🇮🇶", name: "Iraque" },
  { flag: "🇮🇪", name: "Irlanda" },
  { flag: "🇮🇸", name: "Islândia" },
  { flag: "🇮🇱", name: "Israel" },
  { flag: "🇮🇹", name: "Itália" },
  { flag: "🇯🇲", name: "Jamaica" },
  { flag: "🇯🇵", name: "Japão" },
  { flag: "🇯🇴", name: "Jordânia" },
  { flag: "🇰🇪", name: "Quénia" },
  { flag: "🇰🇬", name: "Quirguistão" },
  { flag: "🇰🇼", name: "Kuwait" },
  { flag: "🇱🇦", name: "Laos" },
  { flag: "🇱🇸", name: "Lesoto" },
  { flag: "🇱🇻", name: "Letónia" },
  { flag: "🇱🇧", name: "Líbano" },
  { flag: "🇱🇷", name: "Libéria" },
  { flag: "🇱🇾", name: "Líbia" },
  { flag: "🇱🇮", name: "Liechtenstein" },
  { flag: "🇱🇹", name: "Lituânia" },
  { flag: "🇱🇺", name: "Luxemburgo" },
  { flag: "🇲🇬", name: "Madagáscar" },
  { flag: "🇲🇼", name: "Malawi" },
  { flag: "🇲🇾", name: "Malásia" },
  { flag: "🇲🇻", name: "Maldivas" },
  { flag: "🇲🇱", name: "Mali" },
  { flag: "🇲🇹", name: "Malta" },
  { flag: "🇲🇦", name: "Marrocos" },
  { flag: "🇲🇷", name: "Mauritânia" },
  { flag: "🇲🇽", name: "México" },
  { flag: "🇲🇿", name: "Moçambique" },
  { flag: "🇲🇩", name: "Moldávia" },
  { flag: "🇲🇨", name: "Mónaco" },
  { flag: "🇲🇳", name: "Mongólia" },
  { flag: "🇲🇪", name: "Montenegro" },
  { flag: "🇲🇲", name: "Myanmar" },
  { flag: "🇳🇦", name: "Namíbia" },
  { flag: "🇳🇵", name: "Nepal" },
  { flag: "🇳🇮", name: "Nicarágua" },
  { flag: "🇳🇪", name: "Níger" },
  { flag: "🇳🇬", name: "Nigéria" },
  { flag: "🇳🇴", name: "Noruega" },
  { flag: "🇳🇿", name: "Nova Zelândia" },
  { flag: "🇴🇲", name: "Omã" },
  { flag: "🇳🇱", name: "Países Baixos" },
  { flag: "🇵🇰", name: "Paquistão" },
  { flag: "🇵🇦", name: "Panamá" },
  { flag: "🇵🇬", name: "Papua Nova Guiné" },
  { flag: "🇵🇾", name: "Paraguai" },
  { flag: "🇵🇪", name: "Peru" },
  { flag: "🇵🇱", name: "Polónia" },
  { flag: "🇵🇹", name: "Portugal" },
  { flag: "🇷🇼", name: "Ruanda" },
  { flag: "🇷🇴", name: "Roménia" },
  { flag: "🇷🇺", name: "Rússia" },
  { flag: "🇸🇲", name: "São Marinho" },
  { flag: "🇸🇹", name: "São Tomé e Príncipe" },
  { flag: "🇸🇦", name: "Arábia Saudita" },
  { flag: "🇸🇳", name: "Senegal" },
  { flag: "🇷🇸", name: "Sérvia" },
  { flag: "🇸🇱", name: "Serra Leoa" },
  { flag: "🇸🇬", name: "Singapura" },
  { flag: "🇸🇾", name: "Síria" },
  { flag: "🇸🇴", name: "Somália" },
  { flag: "🇱🇰", name: "Sri Lanka" },
  { flag: "🇸🇿", name: "Suazilândia" },
  { flag: "🇸🇩", name: "Sudão" },
  { flag: "🇸🇸", name: "Sudão do Sul" },
  { flag: "🇸🇪", name: "Suécia" },
  { flag: "🇨🇭", name: "Suíça" },
  { flag: "🇸🇷", name: "Suriname" },
  { flag: "🇹🇯", name: "Tajiquistão" },
  { flag: "🇹🇭", name: "Tailândia" },
  { flag: "🇹🇿", name: "Tanzânia" },
  { flag: "🇹🇱", name: "Timor-Leste" },
  { flag: "🇹🇬", name: "Togo" },
  { flag: "🇹🇹", name: "Trinidad e Tobago" },
  { flag: "🇹🇳", name: "Tunísia" },
  { flag: "🇹🇲", name: "Turquemenistão" },
  { flag: "🇹🇷", name: "Turquia" },
  { flag: "🇺🇬", name: "Uganda" },
  { flag: "🇺🇦", name: "Ucrânia" },
  { flag: "🇺🇾", name: "Uruguai" },
  { flag: "🇺🇿", name: "Uzbequistão" },
  { flag: "🇻🇪", name: "Venezuela" },
  { flag: "🇻🇳", name: "Vietname" },
  { flag: "🇿🇲", name: "Zâmbia" },
  { flag: "🇿🇼", name: "Zimbábue" },
  { flag: "🇬🇧", name: "Reino Unido" },
  { flag: "🇺🇸", name: "Estados Unidos" },
].sort((a, b) => a.name.localeCompare(b.name));

/** Short country list — used for community editing */
export const PAISES_EDIT: Country[] = [
  { flag: "🌍", name: "Internacional" },
  { flag: "🇦🇴", name: "Angola" },
  { flag: "🇦🇷", name: "Argentina" },
  { flag: "🇦🇺", name: "Austrália" },
  { flag: "🇦🇹", name: "Áustria" },
  { flag: "🇧🇷", name: "Brasil" },
  { flag: "🇨🇦", name: "Canadá" },
  { flag: "🇨🇱", name: "Chile" },
  { flag: "🇨🇳", name: "China" },
  { flag: "🇨🇴", name: "Colômbia" },
  { flag: "🇩🇰", name: "Dinamarca" },
  { flag: "🇪🇬", name: "Egito" },
  { flag: "🇪🇸", name: "Espanha" },
  { flag: "🇺🇸", name: "Estados Unidos" },
  { flag: "🇫🇷", name: "França" },
  { flag: "🇬🇷", name: "Grécia" },
  { flag: "🇮🇳", name: "India" },
  { flag: "🇮🇪", name: "Irlanda" },
  { flag: "🇮🇹", name: "Itália" },
  { flag: "🇯🇵", name: "Japão" },
  { flag: "🇲🇽", name: "México" },
  { flag: "🇲🇿", name: "Moçambique" },
  { flag: "🇳🇱", name: "Países Baixos" },
  { flag: "🇵🇪", name: "Peru" },
  { flag: "🇵🇱", name: "Polônia" },
  { flag: "🇵🇹", name: "Portugal" },
  { flag: "🇬🇧", name: "Reino Unido" },
  { flag: "🇷🇺", name: "Rússia" },
  { flag: "🇿🇦", name: "Sul-áfrica" },
  { flag: "🇨🇭", name: "Suíça" },
  { flag: "🇹🇷", name: "Turquia" },
  { flag: "🇺🇦", name: "Ucrânia" },
  { flag: "🇺🇾", name: "Uruguai" },
  { flag: "🇻🇪", name: "Venezuela" },
].sort((a, b) => a.name.localeCompare(b.name));
